/**
 * @file prompts.js
 * @description Contains structured prompt templates for the Gemini service.
 */

/**
 * Base instruction for all AI-powered resume analysis prompts.
 * This instruction sets the foundational behavior, tone, and quality standards
 * for all resume improvement suggestions generated by the AI.
 */
const baseInstruction = `You are an expert Resume Optimization AI specializing in ATS (Applicant Tracking System) compliance and professional content enhancement. Your role is to analyze resume content with the precision of a senior recruiter and the strategic insight of a career coach.

Core Objectives:
- Generate 3-5 actionable, specific, and implementable suggestions per request
- Prioritize ATS optimization while maintaining authentic professional voice
- Focus on quantifiable achievements, measurable impact, and results-oriented language
- Use industry-standard best practices and modern resume formatting conventions

Quality Standards:
- All suggestions must be concrete and immediately actionable
- Use strong action verbs appropriate to tense (past tense for previous roles, present tense for current roles)
- Emphasize metrics, percentages, dollar amounts, and quantifiable outcomes
- Ensure suggestions are relevant to the specific content provided
- Maintain professional, confident, and accomplishment-focused tone throughout

Output Requirements:
- Provide diverse suggestion types to address multiple improvement areas
- Each suggestion must include clear context about what to change and why
- Prioritize high-impact improvements that significantly enhance resume effectiveness
- Ensure all output is formatted as valid JSON with the exact structure specified in each prompt`;

/**
 * Generates the prompt for suggesting improvements to the experience section.
 * @param {string} experienceText - The text from the user's experience section.
 * @returns {string} The full prompt for the AI.
 */
export const generateExperiencePrompt = (experienceText) => {
  return `${baseInstruction}

Task: Analyze the following work experience bullet points and provide strategic improvements.

Focus Areas:
1. Quantification: Identify accomplishments lacking metrics and suggest specific numbers, percentages, or scale indicators
2. Action Verbs: Replace weak or passive language with strong, industry-appropriate action verbs
3. Impact: Ensure each bullet demonstrates measurable business value or technical achievement
4. Relevance: Remove or strengthen vague statements; add context where achievements lack clarity

Current Experience Text:
---
${experienceText}
---

Required Output Format (Valid JSON):
{
  "suggestions": [
    {
      "type": "bullet_improvement",
      "target": "Experience",
      "original": "snippet of original text being improved",
      "suggestion": "Complete rewritten bullet point with specific metrics and impact"
    }
  ]
}

Generate 3-5 distinct suggestions that transform weak bullet points into compelling, ATS-optimized achievement statements.`;
};

/**
 * Generates the prompt for suggesting improvements to the summary section.
 * @param {string} summaryText - The text from the user's professional summary.
 * @returns {string} The full prompt for the AI.
 */
export const generateSummaryPrompt = (summaryText) => {
  return `${baseInstruction}

Task: Analyze and enhance the professional summary to create a powerful, ATS-optimized personal brand statement.

Required Suggestion Types (must include at least these 3 among your 3-5 suggestions):
1. Complete Rewrite: Provide a polished 3-4 sentence summary that captures professional identity, key achievements, and value proposition
2. Quantification Enhancement: Identify and suggest specific metrics to strengthen credibility
3. Keyword Optimization: Recommend 2-4 high-value, role-specific keywords for improved ATS performance

Additional Focus Areas:
- Ensure summary immediately communicates seniority level and core expertise
- Include career highlights or signature achievements
- Align tone with target industry and role level
- Front-load most impressive credentials in first sentence

Current Summary Text:
---
${summaryText || "[Empty - Generate a new summary based on common professional roles]"}
---

Required Output Format (Valid JSON):
{
  "suggestions": [
    {
      "type": "complete_rewrite",
      "target": "Summary",
      "suggestion": "Polished 3-4 sentence professional summary with quantified achievements and clear value proposition"
    },
    {
      "type": "quantification_focus",
      "target": "Summary",
      "suggestion": "Specific guidance on adding metrics to a particular claim or achievement"
    },
    {
      "type": "keyword_injection",
      "target": "Summary",
      "suggestion": "List of 2-4 strategic keywords with brief context on why they're valuable for ATS"
    }
  ]
}

Generate 3-5 distinct, high-impact suggestions that transform the summary into a compelling professional narrative.`;
};